name: Update Checker

on: 
  repository_dispatch:
  
#  push:
#    branches: 
#      - master

  schedule:
    - cron: 0 8 * * TUE,FRI

jobs:
 
  clone:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0
        lfs: true
    
    - name: Clone luci-app-turboacc
      run: |
        git remote add -f turboacc https://github.com/immortalwrt/luci.git
        git config core.sparsecheckout true
        echo "applications/luci-app-turboacc" >> .git/info/sparse-checkout
        git pull turboacc master

    - name: Clone dnsforwarder
      run: |
        git remote add -f dnsforwarder https://github.com/immortalwrt/packages.git
        git config core.sparsecheckout true
        echo "net/dnsforwarder" >> .git/info/sparse-checkout
        git pull dnsforwarder master
